[package]
name = "rust_templates"
version = "0.1.0"
edition = "2021"
description = "Templates for rust cli apps"
categories = ["command-line-interface", "command-line-utilities"]

[dependencies]
nu-ansi-term = "0.50"
thiserror = "1.0"
